import { colors, shadowSpacing } from ".";

export const textShadow = {
  "light-sm": `${shadowSpacing.sm[2]} ${shadowSpacing.sm[2]} 0 ${colors["gray-400"]}`,
  "light-md": `${shadowSpacing.md[2]} ${shadowSpacing.md[2]} 0 ${colors["gray-400"]}`,
  "light-base": `${shadowSpacing.base[2]} ${shadowSpacing.base[2]} 0 ${colors["gray-400"]}`,
  "light-lg": `${shadowSpacing.lg[1]} ${shadowSpacing.lg[1]} 0 ${colors["gray-400"]}`,
  "light-xl": `${shadowSpacing.xl[1]} ${shadowSpacing.xl[1]} 0 ${colors["gray-400"]}`,
  "bold-sm": `-${shadowSpacing.sm[1]} -${shadowSpacing.sm[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.sm[1]} -${shadowSpacing.sm[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.sm[1]} ${shadowSpacing.sm[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.sm[1]} ${shadowSpacing.sm[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.sm[0]} -${shadowSpacing.sm[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.sm[0]} -${shadowSpacing.sm[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.sm[0]} ${shadowSpacing.sm[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.sm[0]} ${shadowSpacing.sm[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.sm[1]} -${shadowSpacing.sm[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.sm[1]} -${shadowSpacing.sm[0]} 0 ${colors["gray-800"]},
    -${shadowSpacing.sm[1]} ${shadowSpacing.sm[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.sm[1]} ${shadowSpacing.sm[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.sm[0]} ${shadowSpacing.sm[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.sm[1]} ${shadowSpacing.sm[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.sm[2]} ${shadowSpacing.sm[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.sm[3]} ${shadowSpacing.sm[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.sm[3]} ${shadowSpacing.sm[2]} 0 ${colors["gray-800"]},
    ${shadowSpacing.sm[3]} ${shadowSpacing.sm[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.sm[3]} ${shadowSpacing.sm[0]} 0 ${colors["gray-800"]}`,
  "bold-md": `-${shadowSpacing.md[1]} -${shadowSpacing.md[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.md[1]} -${shadowSpacing.md[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.md[1]} ${shadowSpacing.md[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.md[1]} ${shadowSpacing.md[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.md[0]} -${shadowSpacing.md[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.md[0]} -${shadowSpacing.md[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.md[0]} ${shadowSpacing.md[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.md[0]} ${shadowSpacing.md[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.md[1]} -${shadowSpacing.md[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.md[1]} -${shadowSpacing.md[0]} 0 ${colors["gray-800"]},
    -${shadowSpacing.md[1]} ${shadowSpacing.md[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.md[1]} ${shadowSpacing.md[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.md[0]} ${shadowSpacing.md[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.md[1]} ${shadowSpacing.md[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.md[2]} ${shadowSpacing.md[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.md[3]} ${shadowSpacing.md[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.md[3]} ${shadowSpacing.md[2]} 0 ${colors["gray-800"]},
    ${shadowSpacing.md[3]} ${shadowSpacing.md[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.md[3]} ${shadowSpacing.md[0]} 0 ${colors["gray-800"]}`,
  "bold-base": `-${shadowSpacing.base[1]} -${shadowSpacing.base[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[1]} -${shadowSpacing.base[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.base[1]} ${shadowSpacing.base[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[1]} ${shadowSpacing.base[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.base[0]} -${shadowSpacing.base[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[0]} -${shadowSpacing.base[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.base[0]} ${shadowSpacing.base[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[0]} ${shadowSpacing.base[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.base[1]} -${shadowSpacing.base[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[1]} -${shadowSpacing.base[0]} 0 ${colors["gray-800"]},
    -${shadowSpacing.base[1]} ${shadowSpacing.base[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[1]} ${shadowSpacing.base[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[0]} ${shadowSpacing.base[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[1]} ${shadowSpacing.base[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[2]} ${shadowSpacing.base[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[3]} ${shadowSpacing.base[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[3]} ${shadowSpacing.base[2]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[3]} ${shadowSpacing.base[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.base[3]} ${shadowSpacing.base[0]} 0 ${colors["gray-800"]}`,
  "bold-lg": `-${shadowSpacing.lg[1]} -${shadowSpacing.lg[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[1]} -${shadowSpacing.lg[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.lg[1]} ${shadowSpacing.lg[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[1]} ${shadowSpacing.lg[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.lg[0]} -${shadowSpacing.lg[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[0]} -${shadowSpacing.lg[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.lg[0]} ${shadowSpacing.lg[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[0]} ${shadowSpacing.lg[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.lg[1]} -${shadowSpacing.lg[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[1]} -${shadowSpacing.lg[0]} 0 ${colors["gray-800"]},
    -${shadowSpacing.lg[1]} ${shadowSpacing.lg[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[1]} ${shadowSpacing.lg[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[0]} ${shadowSpacing.lg[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[1]} ${shadowSpacing.lg[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[2]} ${shadowSpacing.lg[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[3]} ${shadowSpacing.lg[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[3]} ${shadowSpacing.lg[2]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[3]} ${shadowSpacing.lg[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.lg[3]} ${shadowSpacing.lg[0]} 0 ${colors["gray-800"]}`,
  "bold-xl": `-${shadowSpacing.xl[1]} -${shadowSpacing.xl[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[1]} -${shadowSpacing.xl[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.xl[1]} ${shadowSpacing.xl[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[1]} ${shadowSpacing.xl[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.xl[0]} -${shadowSpacing.xl[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[0]} -${shadowSpacing.xl[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.xl[0]} ${shadowSpacing.xl[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[0]} ${shadowSpacing.xl[1]} 0 ${colors["gray-800"]},
    -${shadowSpacing.xl[1]} -${shadowSpacing.xl[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[1]} -${shadowSpacing.xl[0]} 0 ${colors["gray-800"]},
    -${shadowSpacing.xl[1]} ${shadowSpacing.xl[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[1]} ${shadowSpacing.xl[0]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[0]} ${shadowSpacing.xl[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[1]} ${shadowSpacing.xl[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[2]} ${shadowSpacing.xl[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[3]} ${shadowSpacing.xl[3]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[3]} ${shadowSpacing.xl[2]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[3]} ${shadowSpacing.xl[1]} 0 ${colors["gray-800"]},
    ${shadowSpacing.xl[3]} ${shadowSpacing.xl[0]} 0 ${colors["gray-800"]}`,
};
