// ============ LAYOUT STYLES ============
export {
  PageContainer,
  CenteredPage,
  GradientPage,
  ContentWrapper,
  Container,
  MaxWidthContainer,
  FlexCenter,
  FlexBetween,
  FlexColumn,
  FlexRow,
  Grid,
  AutoGrid,
  Section,
  SectionHeader,
  LayoutWithSidebar,
  Sidebar,
  MainContent,
  ImageContainer,
  PageHeader,
} from "./layout.styles";

// ============ CARD STYLES ============
export {
  BaseCard,
  AuthCard as BaseAuthCard,
  StatCard,
  StatIcon,
  StatInfo,
  StatValue,
  StatLabel,
  GameCard,
  InfoCard,
  SlotCard,
  StatsHeader,
} from "./card.styles";

// ============ FORM STYLES ============
export {
  Form,
  FormGroup,
  FormInput,
  FormTextarea,
  FormSelect,
  SubmitButton,
  FormLabel,
  FormError,
  FormHelperText,
  InputWrapper,
  InputIcon,
  InputWithLeftIcon,
  InputWithRightIcon,
} from "./form.styles";

// ============ TYPOGRAPHY STYLES ============
export {
  PageTitle,
  SectionTitle,
  CardTitle,
  Paragraph,
  Subtitle,
  SmallText,
  Link,
  Badge,
  Code,
} from "./typography.styles";

// ============ COMMON STYLES ============
export {
  TabsContainer,
  Tab,
  IconButton,
  ActionButton,
  AddButton,
  Divider,
  VerticalDivider,
  Avatar,
  EmptyState,
  Overlay,
  TooltipWrapper,
  Tooltip,
  SearchContainer,
  StatusBadge,
  OnlineDot,
  ListContainer,
  GridContainer,
  TypeBadge,
  ProgressBar,
  CountBadge,
  Skeleton,
} from "./common.styles";

// ============ ANIMATIONS ============
export {
  float,
  floatSmall,
  pulse,
  pulseRing,
  fadeIn,
  fadeInUp,
  fadeInDown,
  fadeInScale,
  slideInRight,
  slideInLeft,
  slideInUp,
  bounce,
  bounceSmall,
  spin,
  spinSlow,
  shake,
  scaleIn,
  scaleUp,
  glow,
  shimmer,
  pokeballWiggle,
  pokemonAppear,
} from "./animations";

// ============ AUTH STYLES ============
export {
  AuthPage,
  AuthContainer,
  AuthCard,
  AuthHeader,
  AuthLogo,
  AuthTitle,
  AuthSubtitle,
  AuthForm,
  AuthInput,
  AuthSubmit,
  AuthDivider,
  SocialButton,
  SocialButtonsGroup,
  AuthFooter,
  AuthRow,
  AuthSmallText,
  AuthLink,
  CheckboxLabel,
  TwoFactorContainer,
  TwoFactorInput,
  AuthMessage,
  PasswordWrapper,
  PasswordToggle,
  PasswordInput,
} from "./auth.styles";
